#!/usr/bin/env python3

from __future__ import annotations

import asyncio
import logging
import time
import tomllib

from datetime import timedelta
from pathlib import Path
from typing import Annotated

import aiofiles

from pydantic import AliasChoices, BaseModel, DirectoryPath, Field
from pydantic_settings import BaseSettings, CliSubCommand, SettingsConfigDict, CliApp
from sqlalchemy import CheckConstraint, ForeignKey, MetaData, Column, String, Index, column, select, text
from sqlalchemy.dialects.sqlite import insert
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine
from sqlalchemy.sql.functions import coalesce

from dats import DAT_OBJECT_TYPES, index_dats, Rom as DatRom
from igdb import Playlist, PlaylistConfig, IGDB_OBJECT_TYPES, index_igdb
from hasheous import HASHEOUS_OBJECT_TYPES, index_hasheous
from utils import CliTuple, DEFAULT_DAT_CONCURRENCY, DEFAULT_HASHEOUS_CONCURRENCY, DEFAULT_IGDB_CONCURRENCY, IndexArgs, PlaylistArgs, PoolArgs, RowId, Sha256, VerboseArgs, create_db, create_deferred_indexes, DatabaseModel, Crc, Md5, Sha1, db_transaction

class AllRoms(DatabaseModel, frozen=True):
    __tablename__ = "AllRoms"
    __tableargs__ = (
        CheckConstraint("dat_rom IS NOT NULL OR hasheous_rom IS NOT NULL", name="dat_or_hasheous_rom_not_null"),
        Index("ix_AllRoms", "dat_rom", "hasheous_rom", "crc", "serial", "md5", "sha1", unique=True),
        Index("ix_AllRoms_dat_rom_where_not_null", "dat_rom", unique=True, sqlite_where=column("dat_rom").is_not(None)),
        Index("ix_AllRoms_hasheous_rom_where_not_null", "hasheous_rom", unique=True, sqlite_where=column("hasheous_rom").is_not(None)),
        Index("ix_AllRoms_dat_rom_crc_where_not_null", "dat_rom", "crc", unique=True, sqlite_where=column("crc").is_not(None) & column("dat_rom").is_not(None)),
        Index("ix_AllRoms_hasheous_crc_where_not_null", "hasheous_rom", "crc", unique=True, sqlite_where=column("crc").is_not(None) & column("hasheous_rom").is_not(None)),
        Index("ix_AllRoms_serial_where_not_null", "serial", sqlite_where=column("serial").is_not(None)),
        Index("ix_AllRoms_dat_rom_md5_where_not_null", "dat_rom", "md5", unique=True, sqlite_where=column("md5").is_not(None) & column("dat_rom").is_not(None)),
        Index("ix_AllRoms_hasheous_rom_md5_where_not_null", "hasheous_rom", "md5", unique=True, sqlite_where=column("md5").is_not(None) & column("hasheous_rom").is_not(None)),
        Index("ix_AllRoms_dat_rom_sha1_where_not_null", "dat_rom", "sha1", unique=True, sqlite_where=column("sha1").is_not(None) & column("dat_rom").is_not(None)),
        Index("ix_AllRoms_hasheous_rom_sha1_where_not_null", "hasheous_rom", "sha1", unique=True, sqlite_where=column("sha1").is_not(None) & column("hasheous_rom").is_not(None)),
    )

    dat_rom: Annotated[RowId | None, Column(ForeignKey("DatRom.rowid"), nullable=True, index=True, unique=True)] = None
    hasheous_rom: Annotated[int | None, Column(ForeignKey("HasheousRomItem.id"), nullable=True, index=True, unique=True)] = None
    crc: Annotated[Crc | None, Column(String, nullable=True, index=True, unique=True)] = None
    serial: Annotated[str | None, Column(String, nullable=True, index=True)] = None
    md5: Annotated[Md5 | None, Column(String, nullable=True, index=True, unique=True)] = None
    sha1: Annotated[Sha1 | None, Column(String, nullable=True, index=True, unique=True)] = None

PARENT_DIR = Path(__file__).parent.parent
class CommonArgs:
    igdb_path: DirectoryPath = Field(
        default=PARENT_DIR / 'tmp' / 'igdb',
        description="Path to the directory containing IGDB JSON files fetched with `igdb.py fetch`.",
        validation_alias=AliasChoices('i', 'igdb'),
        validate_default=True,
    )

    hasheous_path: DirectoryPath = Field(
        default=PARENT_DIR / 'tmp' / 'hasheous',
        description="Path to the directory containing Hasheous ZIP dumps fetched with `hasheous.py fetch`.",
        validation_alias=AliasChoices('s', 'hasheous'),
        validate_default=True,
    )

    dat_dirs: CliTuple[DirectoryPath] = Field(
        default=(PARENT_DIR / 'dat', PARENT_DIR / 'metadat',),
        description="Paths to the directories containing existing DAT files to scan for games to process.",
        validation_alias=AliasChoices('d', 'dat'),
        validate_default=True,
    )

OUTDIR_NAME = "lookatalldat"

class GenerateSubCommand(BaseModel, PlaylistArgs, CommonArgs, VerboseArgs):
    input: Path = Field(
        default=PARENT_DIR / 'tmp' / 'index.db',
        description="Path to the input SQLite database file, as generated by the `index` subcommand.",
        validation_alias=AliasChoices('i', 'input'),
        validate_default=True,
    )

    outdir: DirectoryPath = Field(
        default=PARENT_DIR / OUTDIR_NAME,
        description="Path to the output directory where generated DAT files will be written.",
        validation_alias=AliasChoices('o', 'outdir'),
        validate_default=True,
    )

    _log = logging.getLogger('match.index')

    async def cli_cmd(self) -> None:
        start = time.perf_counter()

        self._log.setLevel(logging.DEBUG if self.verbose else logging.INFO)
        self._log.addHandler(log_handler)
        if self.verbose:
            # Log the SQL table creation statements being executed,
            # but we'll lower the level later during data insertion
            # so we don't get overwhelmed with output.
            sqlalchemy_engine_log.setLevel(logging.INFO)

        db = create_async_engine(
            f"sqlite+aiosqlite:///{self.input}",
            connect_args={
                "check_same_thread": False,
                "autocommit": False,
                "mode": "ro",
            },
        )
        # TODO: use create_db

        async with aiofiles.open(self.config, "r") as config_file:
            config = PlaylistConfig.model_validate(tomllib.loads(await config_file.read()))

        if self.playlists:
            playlists = tuple(p for p in config.playlists if p.title in self.playlists)
        else:
            playlists = config.playlists

        metadata = MetaData()
        for model_type in MODEL_TYPES:
            model_type.create_tables(metadata)

        async with asyncio.TaskGroup() as group:
            for playlist in playlists:
                group.create_task(
                    self._generate_dat(db=db, metadata=metadata, playlist_data=playlist),
                    name=playlist.title
                )

        await db.dispose()
        end = time.perf_counter()
        elapsed = timedelta(seconds=end - start)
        self._log.info(f"Elapsed time: %s", elapsed)

    async def _generate_dat(self, db: AsyncEngine, metadata: MetaData, playlist_data: Playlist) -> None:
        # No database locking this time, since we're only querying it
        async with db.begin() as tx:
            # TODO: Run a particular SELECT query or view (need to decide how) to get the ROMs
            # TODO: Construct DatRoms for each ROM
            # TODO: Run another SELECT to get the games associated with the ROMs
            # TODO: Construct DatGames for each game, associating the appropriate DatRoms with each DatGame
            # TODO: Store the DatGames and DatRoms in a ParsedDatFile
            # TODO: Write the ParsedDatFile to disk as a .dat file in the output directory, with a filename based on the playlist title
            pass


MODEL_TYPES = (
    *IGDB_OBJECT_TYPES,
    *HASHEOUS_OBJECT_TYPES,
    *DAT_OBJECT_TYPES,
    AllRoms,
)

log_handler = logging.StreamHandler()
log_handler.setFormatter(logging.Formatter('[%(asctime)s][%(name)s][%(taskName)s] %(message)s'))
sqlalchemy_engine_log = logging.getLogger('sqlalchemy.engine.Engine')
sqlalchemy_engine_log.addHandler(log_handler)


class IndexSubCommand(BaseModel, CommonArgs, PlaylistArgs, IndexArgs, PoolArgs, VerboseArgs):
    """Build a single SQLite index database containing IGDB, DAT, and Hasheous data."""

    output: Path = Field(
        default=PARENT_DIR / 'tmp' / 'index.db',
        description="Path to the output SQLite database file.",
        validation_alias=AliasChoices('o', 'output'),
        validate_default=True,
    )

    _db_lock = asyncio.Lock()
    _log = logging.getLogger('match.index')

    async def cli_cmd(self) -> None:
        start = time.perf_counter()

        self._log.setLevel(logging.DEBUG if self.verbose else logging.INFO)
        self._log.addHandler(log_handler)
        logging.getLogger('hasheous.index').setLevel(logging.DEBUG if self.verbose else logging.INFO)
        logging.getLogger('hasheous.index').addHandler(log_handler)
        logging.getLogger('igdb.index').setLevel(logging.DEBUG if self.verbose else logging.INFO)
        logging.getLogger('igdb.index').addHandler(log_handler)
        logging.getLogger('dats.index').setLevel(logging.DEBUG if self.verbose else logging.INFO)
        logging.getLogger('dats.index').addHandler(log_handler)

        if self.verbose:
            sqlalchemy_engine_log.setLevel(logging.INFO)

        self.output.parent.mkdir(parents=True, exist_ok=True)

        if self.output.exists() and not self.force:
            raise FileExistsError(f"Output database file '{self.output}' already exists. Use --force to overwrite.")

        # Remove existing database file if it exists
        self.output.unlink(missing_ok=True)

        async with aiofiles.open(self.config, "r") as config_file:
            config = PlaylistConfig.model_validate(tomllib.loads(await config_file.read()))

        if self.playlists:
            playlists = tuple(p for p in config.playlists if p.title in self.playlists)
        else:
            playlists = config.playlists

        # Create a single database with tables for all three data sources
        db, metadata = await create_db(self.output, MODEL_TYPES)
        sqlalchemy_engine_log.setLevel(logging.WARNING)

        # Run all three indexing tasks concurrently against the same database

        async with self.create_pool() as pool:
            async with asyncio.TaskGroup() as group:
                dat_task = group.create_task(
                    index_dats(db=db, metadata=metadata, db_lock=self._db_lock, playlists=playlists, dat_dirs=self.dat_dirs, pool=pool),
                    name="DATs"
                )
                igdb_task = group.create_task(
                    index_igdb(db=db, metadata=metadata, db_lock=self._db_lock, playlists=playlists, igdb_path=self.igdb_path, pool=pool),
                    name="IGDB"
                )
                hasheous_task = group.create_task(
                    index_hasheous(db=db, metadata=metadata, db_lock=self._db_lock, playlists=playlists, hasheous_path=self.hasheous_path, pool=pool),
                    name="Hasheous"
                )

                # ...but once the DAT and Hasheous tasks are finished,
                # we can start combining their ROM data into one table.
                # (IGDB doesn't have ROM data, so we don't need to wait for it.)
                await dat_task
                await hasheous_task

                await group.create_task(
                    self._insert_allrom_mappings(db=db, db_lock=self._db_lock, metadata=metadata),
                    name="AllRoms"
                )

        async with db.connect() as connection:
            # Run the SQLite optimizer to improve performance on all tables (0x10000),
            # but don't take too long (0x00010)
            await connection.execute(text("PRAGMA optimize = 0x10012"))

        # Close the engine
        await db.dispose()

        end = time.perf_counter()
        elapsed = timedelta(seconds=end - start)
        self._log.info(f"Elapsed time: %s", elapsed)

    async def _insert_allrom_mappings(self, db: AsyncEngine, db_lock: asyncio.Lock, metadata: MetaData) -> None:
        self._log.debug("Aggregating ROM data into one table")
        mapping_table = metadata.tables[AllRoms.__tablename__]
        insert_mapping = insert(mapping_table)

        # TODO: Fetch all ROMs from DatRom
        async with db_transaction(db, db_lock) as tx:
            datrom = metadata.tables[DatRom.__tablename__]
            datrom_results = await tx.execute(
                datrom.select().with_only_columns(
                    datrom.c.rowid.label("dat_rom"),
                    datrom.c.crc,
                    datrom.c.serial,
                    datrom.c.md5,
                    datrom.c.sha1
                )
            )
            datrom_mappings = (AllRoms(**mapping) for mapping in datrom_results.mappings().all())

        async with db_transaction(db, db_lock) as tx:
            await tx.execute(
                insert_mapping.on_conflict_do_update(set_={

                    "dat_rom": coalesce(mapping_table.columns.dat_rom, insert_mapping.excluded.dat_rom),
                    "hasheous_rom": coalesce(mapping_table.columns.hasheous_rom, insert_mapping.excluded.hasheous_rom),
                    "crc": coalesce(mapping_table.columns.crc, insert_mapping.excluded.crc),
                    "md5": coalesce(mapping_table.columns.md5, insert_mapping.excluded.md5),
                    "serial": coalesce(mapping_table.columns.serial, insert_mapping.excluded.serial),
                    "sha1": coalesce(mapping_table.columns.sha1, insert_mapping.excluded.sha1),
                }),
                [m.as_row for m in datrom_mappings]
            )
            await tx.commit()

        # TODO: Fetch all ROMs from HasheousRomItem
        async with db_transaction(db, db_lock) as tx:
            hasheousrom = metadata.tables["HasheousRomItem"]
            hasheousrom_results = await tx.execute(
                hasheousrom.select().with_only_columns(
                    hasheousrom.c.id.label("hasheous_rom"),
                    hasheousrom.c.crc,
                    hasheousrom.c.serial,
                    hasheousrom.c.md5,
                    hasheousrom.c.sha1
                )
            )
            hasheousrom_mappings = (AllRoms(**mapping) for mapping in hasheousrom_results.mappings().all())

        async with db_transaction(db, db_lock) as tx:
            await tx.execute(
                insert_mapping.on_conflict_do_update(set_={
                    "dat_rom": coalesce(mapping_table.columns.dat_rom, insert_mapping.excluded.dat_rom),
                    "hasheous_rom": coalesce(mapping_table.columns.hasheous_rom, insert_mapping.excluded.hasheous_rom),
                    "crc": coalesce(mapping_table.columns.crc, insert_mapping.excluded.crc),
                    "md5": coalesce(mapping_table.columns.md5, insert_mapping.excluded.md5),
                    "serial": coalesce(mapping_table.columns.serial, insert_mapping.excluded.serial),
                    "sha1": coalesce(mapping_table.columns.sha1, insert_mapping.excluded.sha1),
                }),
                [m.as_row for m in hasheousrom_mappings]
            )
            await tx.commit()


class MatchCommand(BaseSettings):
    generate: CliSubCommand[GenerateSubCommand]
    index: CliSubCommand[IndexSubCommand]

    model_config = SettingsConfigDict(
        case_sensitive=False,
        cli_avoid_json=True,
        cli_implicit_flags=True,
        cli_kebab_case=True,
        cli_parse_args=True,
        extra="ignore",
    )

    def cli_cmd(self):
        CliApp.run_subcommand(self)

if __name__ == "__main__":
    CliApp.run(MatchCommand)