#!/usr/bin/env python3

from __future__ import annotations

import asyncio
import logging
import time
import tomllib

from collections.abc import Callable, Collection, Iterable
from datetime import timedelta
from pathlib import Path
from typing import NamedTuple, Optional
from warnings import deprecated

import aiofiles

from pydantic import AliasChoices, BaseModel, DirectoryPath, Field
from pydantic_settings import BaseSettings, CliSubCommand, SettingsConfigDict, CliApp
from sqlalchemy import MetaData, text
from sqlalchemy.ext.asyncio import create_async_engine

from dats import DAT_OBJECT_TYPES, Game as DatGame, index_dats
from igdb import Game as IgdbGame, Playlist, PlaylistConfig, IGDB_OBJECT_TYPES, index_igdb

from hasheous import HASHEOUS_OBJECT_TYPES, DataObject, MatchRecord, index_hasheous
from utils import IndexArgs, PlaylistArgs, PoolArgs, VerboseArgs, create_db

class PlaylistData(NamedTuple):
    playlist: Playlist
    igdb: Collection[IgdbGame]
    dats: Collection[DatGame]
    hasheous: Collection[DataObject]

class GameMatch(NamedTuple):
    source_dat: DatGame
    igdb: Optional[IgdbGame]
    hasheous: Optional[DataObject]
    generated_dat: Optional[DatGame]
    record: MatchRecord

@deprecated("Use more_itertools.first_true instead")
def find[T](items: Iterable[T] | None, predicate: Callable[[T], bool]) -> T | None:
    """Find the first item in items that matches the predicate, or None if not found."""
    if items is None:
        return None

    for item in items:
        if predicate(item):
            return item

    return None

PARENT_DIR = Path(__file__).parent.parent
class CommonArgs:
    igdb_path: DirectoryPath = Field(
        default=PARENT_DIR / 'tmp' / 'igdb',
        description="Path to the directory containing IGDB JSON files fetched with `igdb.py fetch`.",
        validation_alias=AliasChoices('i', 'igdb'),
        validate_default=True,
    )

    hasheous_path: DirectoryPath = Field(
        default=PARENT_DIR / 'tmp' / 'hasheous',
        description="Path to the directory containing Hasheous ZIP dumps fetched with `hasheous.py fetch`.",
        validation_alias=AliasChoices('s', 'hasheous'),
        validate_default=True,
    )

    dat_dirs: tuple[DirectoryPath, ...] = Field(
        default=(PARENT_DIR / 'dat', PARENT_DIR / 'metadat',),
        description="Paths to the directories containing existing DAT files to scan for games to process.",
        validation_alias=AliasChoices('d', 'dat'),
        validate_default=True,
    )


class GenerateSubCommand(BaseModel, CommonArgs, VerboseArgs):
    input: Path = Field(
        default=PARENT_DIR / 'tmp' / 'index.db',
        description="Path to the input SQLite database file, as generated by the `index` subcommand.",
        validation_alias=AliasChoices('i', 'input'),
        validate_default=True,
    )

    _log = logging.getLogger('match.index')

    async def cli_cmd(self) -> None:
        start = time.perf_counter()

        self._log.setLevel(logging.DEBUG if self.verbose else logging.INFO)
        self._log.addHandler(log_handler)
        if self.verbose:
            # Log the SQL table creation statements being executed,
            # but we'll lower the level later during data insertion
            # so we don't get overwhelmed with output.
            sqlalchemy_engine_log.setLevel(logging.INFO)

        db = create_async_engine(
            f"sqlite+aiosqlite:///{self.input}",
            connect_args={
                "check_same_thread": False,
                "autocommit": False,
            },
        )

        metadata = MetaData()
        for model_type in MODEL_TYPES:
            model_type.create_tables(metadata)

        # TODO: For each playlist, issue a SELECT


MODEL_TYPES = (
    *IGDB_OBJECT_TYPES,
    *HASHEOUS_OBJECT_TYPES,
    *DAT_OBJECT_TYPES,
)

log_handler = logging.StreamHandler()
log_handler.setFormatter(logging.Formatter('[%(asctime)s][%(name)s][%(taskName)s] %(message)s'))
sqlalchemy_engine_log = logging.getLogger('sqlalchemy.engine.Engine')
sqlalchemy_engine_log.addHandler(log_handler)


class IndexSubCommand(BaseModel, CommonArgs, PlaylistArgs, IndexArgs, PoolArgs, VerboseArgs):
    """Build a single SQLite index database containing IGDB, DAT, and Hasheous data."""

    output: Path = Field(
        default=PARENT_DIR / 'tmp' / 'index.db',
        description="Path to the output SQLite database file.",
        validation_alias=AliasChoices('o', 'output'),
        validate_default=True,
    )

    _db_lock = asyncio.Lock()
    _log = logging.getLogger('match.index')

    async def cli_cmd(self) -> None:
        start = time.perf_counter()

        self._log.setLevel(logging.DEBUG if self.verbose else logging.INFO)
        self._log.addHandler(log_handler)
        logging.getLogger('hasheous.index').setLevel(logging.DEBUG if self.verbose else logging.INFO)
        logging.getLogger('hasheous.index').addHandler(log_handler)
        logging.getLogger('igdb.index').setLevel(logging.DEBUG if self.verbose else logging.INFO)
        logging.getLogger('igdb.index').addHandler(log_handler)
        logging.getLogger('dats.index').setLevel(logging.DEBUG if self.verbose else logging.INFO)
        logging.getLogger('dats.index').addHandler(log_handler)

        if self.verbose:
            sqlalchemy_engine_log.setLevel(logging.INFO)

        self.output.parent.mkdir(parents=True, exist_ok=True)

        if self.output.exists() and not self.force:
            raise FileExistsError(f"Output database file '{self.output}' already exists. Use --force to overwrite.")

        # Remove existing database file if it exists
        self.output.unlink(missing_ok=True)

        async with aiofiles.open(self.config, "r") as config_file:
            config = PlaylistConfig.model_validate(tomllib.loads(await config_file.read()))

        if self.playlists:
            playlists = tuple(p for p in config.playlists if p.title in self.playlists)
        else:
            playlists = config.playlists

        # Create a single database with tables for all three data sources
        db, metadata = await create_db(self.output, MODEL_TYPES)
        sqlalchemy_engine_log.setLevel(logging.WARNING)

        # Run all three indexing tasks concurrently against the same database

        async with self.create_pool() as pool:
            async with asyncio.TaskGroup() as group:
                group.create_task(
                    index_dats(db=db, metadata=metadata, db_lock=self._db_lock, playlists=playlists, dat_dirs=self.dat_dirs, pool=pool),
                    name="DATs"
                )
                group.create_task(
                    index_igdb(db=db, metadata=metadata, db_lock=self._db_lock, playlists=playlists, igdb_path=self.igdb_path, pool=pool),
                    name="IGDB"
                )
                group.create_task(
                    index_hasheous(db=db, metadata=metadata, db_lock=self._db_lock, playlists=playlists, hasheous_path=self.hasheous_path, pool=pool),
                    name="Hasheous"
                )

        async with db.connect() as connection:
            # Run the SQLite optimizer to improve performance on all tables (0x10000),
            # but don't take too long (0x00010)
            await connection.execute(text("PRAGMA optimize = 0x10012"))

        # Close the engine
        await db.dispose()

        end = time.perf_counter()
        elapsed = timedelta(seconds=end - start)
        self._log.info(f"Elapsed time: %s", elapsed)


class MatchCommand(BaseSettings):
    generate: CliSubCommand[GenerateSubCommand]
    index: CliSubCommand[IndexSubCommand]

    model_config = SettingsConfigDict(
        case_sensitive=False,
        cli_avoid_json=True,
        cli_implicit_flags=True,
        cli_kebab_case=True,
        cli_parse_args=True,
        extra="ignore",
    )

    def cli_cmd(self):
        CliApp.run_subcommand(self)


__all__ = ("PlaylistData", "GameMatch", "MatchRecord")

if __name__ == "__main__":
    CliApp.run(MatchCommand)